library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- =============================================================
--  NRZL_Source
--  - Reads 16-bit switch vector on button press
--  - Mirrors the captured word on leds_out
--  - Drives a 1920x1080 @60 Hz VGA output:
--      full screen GREEN  when nrzl_out = '1'
--      full screen BLACK  when nrzl_out = '0'
--  Clock Wizard: 100 MHz in → 148.5 MHz out (clk148)
-- =============================================================

entity NRZL_Source is
    Generic (
        ciclos : INTEGER := 50_000_000   -- bit period at 100 MHz
    );
    Port (
        clk      : in  STD_LOGIC;                      -- 100 MHz board clock
        btn      : in  STD_LOGIC;                      -- debounced capture button
        o_swv    : in  STD_LOGIC_VECTOR(15 downto 0);  -- switches

        leds_out : out STD_LOGIC_VECTOR(15 downto 0);  -- LED mirror
        nrzl_out : out STD_LOGIC;                      

        -- VGA (1920x1080 @60 Hz)
        hsync    : out STD_LOGIC;
        vsync    : out STD_LOGIC;
        vgaGreen : out STD_LOGIC_VECTOR(3 downto 0);
        vgaBlue  : out STD_LOGIC_VECTOR(3 downto 0);
        vgaRed   : out STD_LOGIC_VECTOR(3 downto 0)
    );
end NRZL_Source;

architecture Behavioral of NRZL_Source is

    -- =========================================================
    --  Clock Wizard component declaration
    --  Generated by Vivado IP Catalog:
    --    Input  : 100.000 MHz  (clk_in1)
    --    Output : 148.500 MHz  (clk_out1)  → VGA pixel clock
    -- =========================================================
    component clk_wiz_0
        port (
            clk_out1 : out STD_LOGIC;
            reset    : in  STD_LOGIC;   -- active-high wizard reset
            locked   : out STD_LOGIC;
            clk_in1  : in  STD_LOGIC
        );
    end component;

    -- =========================================================
    --  VGA 1920×1080 @60 Hz  (pixel clock ≈ 148.5 MHz)
    -- =========================================================
    constant H_VISIBLE : integer := 1920;
    constant H_FRONT   : integer :=   88;
    constant H_SYNC    : integer :=   44;
    constant H_BACK    : integer :=  148;
    constant H_TOTAL   : integer := 2200;   -- 1920+88+44+148

    constant V_VISIBLE : integer := 1080;
    constant V_FRONT   : integer :=    4;
    constant V_SYNC    : integer :=    5;
    constant V_BACK    : integer :=   36;
    constant V_TOTAL   : integer := 1125;   -- 1080+4+5+36

    signal clk148  : STD_LOGIC := '0';
    signal wiz_locked : STD_LOGIC;

    signal h_count : integer range 0 to H_TOTAL - 1 := 0;
    signal v_count : integer range 0 to V_TOTAL - 1 := 0;

    signal video_on : STD_LOGIC := '0';

    -- =========================================================
    --  Debounce
    -- =========================================================
    constant DEBOUNCE_MAX : integer := 500_000;

    signal db_cnt     : integer range 0 to DEBOUNCE_MAX := 0;
    signal btn_stable : STD_LOGIC := '0';
    signal btn_prev   : STD_LOGIC := '0';

    -- =========================================================
    --  NRZ-L state
    -- =========================================================
    signal reset_n      : STD_LOGIC := '0';   -- '0' = transmitting, '1' = idle/reset
    signal bit_counter  : integer range 0 to ciclos - 1 := 0;
    signal bit_index    : integer range 0 to 15 := 15;  -- MSB first

    signal captured_swv : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');

    signal nrzl_reg     : STD_LOGIC := '0';   -- internal copy for VGA to read

begin

    -- =========================================================
    --  Clock Wizard instantiation
    --  The wizard's "reset" port is active-high; tie to '0' so
    --  it starts freely. Use "locked" to optionally gate logic.
    -- =========================================================
    u_clk_wiz : clk_wiz_0
        port map (
            clk_in1  => clk,
            clk_out1 => clk148,
            reset    => '0',
            locked   => wiz_locked
        );

    -- =========================================================
    --  Debounce + capture + toggle
    --
    --  On each rising edge of btn_stable (button press):
    --    • Capture o_swv into captured_swv
    --    • Toggle reset_n: '1' stops TX, '0' starts TX
    --  This means the first press captures & starts; the second
    --  press stops; the third press captures fresh & starts, etc.
    -- =========================================================
    p_debounce_toggle : process(clk)
    begin
        if rising_edge(clk) then

            -- Debounce counter
            if btn = btn_stable then
                db_cnt <= 0;
            else
                if db_cnt = DEBOUNCE_MAX - 1 then
                    db_cnt     <= 0;
                    btn_stable <= btn;
                else
                    db_cnt <= db_cnt + 1;
                end if;
            end if;

            btn_prev <= btn_stable;

            -- Rising edge of debounced button
            if btn_stable = '1' and btn_prev = '0' then
                -- Capture switches BEFORE toggling so the just-read
                -- value is always what gets transmitted next
                if reset_n = '1' then
                    -- Was stopped → capture new word and start
                    captured_swv <= o_swv;
                end if;
                reset_n <= not reset_n;
            end if;

        end if;
    end process;

    -- =========================================================
    --  NRZ-L modulation  (synchronous reset, MSB-first)
    --
    --  reset_n = '1'  →  idle: output low, counters cleared
    --  reset_n = '0'  →  transmit: cycle through bits 15..0
    -- =========================================================
    p_nrzl : process(clk)
    begin
        if rising_edge(clk) then

            if reset_n = '1' then
                -- Idle / reset state
                bit_counter <= 0;
                bit_index   <= 15;
                nrzl_reg    <= '0';
                leds_out    <= (others => '0');

            else
                -- Drive current bit
                nrzl_reg <= captured_swv(bit_index);
                leds_out <= captured_swv;

                if bit_counter = ciclos - 1 then
                    bit_counter <= 0;

                    -- Advance to next bit (MSB → LSB, then wrap)
                    if bit_index = 0 then
                        bit_index <= 15;
                    else
                        bit_index <= bit_index - 1;
                    end if;
                else
                    bit_counter <= bit_counter + 1;
                end if;
            end if;

        end if;
    end process;

    nrzl_out <= nrzl_reg;

    -- =========================================================
    --  VGA Timing  (clocked by 148.5 MHz pixel clock)
    -- =========================================================
    p_vga_timing : process(clk148)
    begin
        if rising_edge(clk148) then
            if h_count = H_TOTAL - 1 then
                h_count <= 0;

                if v_count = V_TOTAL - 1 then
                    v_count <= 0;
                else
                    v_count <= v_count + 1;
                end if;
            else
                h_count <= h_count + 1;
            end if;
        end if;
    end process;

    -- =========================================================
    --  Sync signals  (active-low for VGA compatibility)
    -- =========================================================
    hsync <= '0' when (h_count >= H_VISIBLE + H_FRONT and
                       h_count <  H_VISIBLE + H_FRONT + H_SYNC)
             else '1';

    vsync <= '0' when (v_count >= V_VISIBLE + V_FRONT and
                       v_count <  V_VISIBLE + V_FRONT + V_SYNC)
             else '1';

    -- =========================================================
    --  Active-video flag
    -- =========================================================
    video_on <= '1' when (h_count < H_VISIBLE and v_count < V_VISIBLE)
                else '0';

    -- =========================================================
    --  VGA Pixel output
    --  Full screen GREEN when nrzl_reg = '1'
    --  Full screen BLACK when nrzl_reg = '0'  (or blanking)
    -- =========================================================
    vgaGreen <= "1111" when (video_on = '1' and nrzl_reg = '1')
                else "1100";
    vgaRed <= "1111" when (video_on = '1' and nrzl_reg = '1')
                else "0000";
    vgaBlue <= "1111" when (video_on = '1' and nrzl_reg = '1')
                else "0000";

end Behavioral;